sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: 4hui5VezUMnAboH6xK79abQ1EK/L27ofFG7GN0GdyQd2GZ/yoXmcHI1EGfJGZ4LksV4/MzKiXhjy6aaQYPj20ei8TwFlCB0ILYxnVzqEsF+jZ0oCK4g+V+tmaGnfkb8raRJxZKErm+pN0lr/MiU9h/d6nLcEV+QZTHhyUqO4MtQ=
