sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: erf4mEZaRlWQKG1R5oz6u/dzueRF+ZMWiq+DgSdagH9OhP89+7qHfyfVlCiRy5Otqthe56XGWLrTCcIuo7YD3q9vhjvaPAWmiw26P6IrFO5snSrndcaoD9PSuCbSG+LK5Cvxp8nmYb4mbA/3QoeyVl78k6jww+5RnC7ftj8Abv0=
